[font]
size = 20.0
normal = {family = "Dank Mono"}

[cursor.style]
blinking = "On"

[window]
# Pass alt key into Zellij
# https://zellij.dev/documentation/faq.html#i-am-a-macos-user-how-can-i-use-the-alt-key
option_as_alt = "Both"
decorations = "Buttonless"
dynamic_padding = false

[window.padding]
x = 10
y = 10

# Default colors
[colors.primary]
background = "#011627"
foreground = "#d6deeb"

# Cursor colors
[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "#22da6e"

# Search colors
[colors.search.matches]
foreground = "#000000"
background = "#22da6e"

[colors.search.focused_match]
foreground = "#ffffff"
background = "#22da6e"

[colors.footer_bar]
foreground = "#ffffff"
background = "#1d3b53"

# Selection colors
[colors.selection]
  text = "CellBackground"
  background = "CellForeground"
  # text = "#ffffff"
  # background = "#0d486e"
  # cursor = "CellForeground"

# Normal colors
[colors.normal]
black = "#011627"
red = "#EF5350"
green = "#22da6e"
yellow = "#c5e478"
blue = "#82AAFF"
magenta = "#C792EA"
cyan = "#21c7a8"
white = "#ffffff"

# Bright colors
[colors.bright]
black = "#575656"
red = "#EF5350"
green = "#22da6e"
yellow = "#ffeb95"
blue = "#82AAFF"
magenta = "#C792EA"
cyan = "#7fdbca"
white = "#ffffff"
