local WindowManager = require("window-management/helpers")

-- Center
hs.hotkey.bind({ "ctrl", "alt" }, "c", function()
  local window = hs.window.focusedWindow()
  window:centerOnScreen(nil, true)
end)

hs.hotkey.bind({ "ctrl", "alt" }, "h", function()
  WindowManager.startMoving("left")
end, function()
  WindowManager.stopMoving()
end)
hs.hotkey.bind({ "ctrl", "alt" }, "j", function()
  WindowManager.startMoving("down")
end, function()
  WindowManager.stopMoving()
end)
hs.hotkey.bind({ "ctrl", "alt" }, "k", function()
  WindowManager.startMoving("up")
end, function()
  WindowManager.stopMoving()
end)
hs.hotkey.bind({ "ctrl", "alt" }, "l", function()
  WindowManager.startMoving("right")
end, function()
  WindowManager.stopMoving()
end)
