local capabilities = require("lsp.capabilities")
local on_attach = require("lsp.on_attach")
local helpers = require("custom-helpers")

-- Ignore sorbet autogen directories
do
  local defaultHandler = vim.lsp.handlers["textDocument/definition"]

  -- Wrap the default definition handler
  vim.lsp.handlers["textDocument/definition"] = function(err, method, locations, client_id, bufnr, config)
    if locations == nil or vim.tbl_isempty(locations) then
      return
    end

    -- Filter out `sorbet/shims/autogenerated` if we match more than 1 definition
    -- location.
    if #locations > 1 then
      locations = vim.tbl_filter(function(item)
        local matches_autogen = item["uri"]:match("autogenerated")
        return not matches_autogen
      end, locations)
    end

    defaultHandler(err, method, locations, client_id, bufnr, config)
  end
end

if not helpers.isModuleAvailable("stripe") then
  require("lspconfig").sorbet.setup({
    capabilities = capabilities,
    on_attach = on_attach,
  })
end
