# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # # Simple text replacement
  # - trigger: ":espanso"
  #   replace: "Hi there!"

  # # Dates
  # - trigger: ":date"
  #   replace: "{{mydate}}"
  #   vars:
  #     - name: mydate
  #       type: date
  #       params:
  #         format: "%m/%d/%Y"

  # # Shell commands
  # - trigger: ":shell"
  #   replace: "{{output}}"
  #   vars:
  #     - name: output
  #       type: shell
  #       params:
  #         cmd: "echo Hello from your shell"

  #TeX shorthands
  - trigger: "\\/"
    replace: "\\frac{"
  - trigger: "\\ket"
    replace: "|$|$\\rangle"
  - trigger: "\\)"
    replace: "\\right)"
  - trigger: "\\("
    replace: "\\left("

  # TeX to Unicode shorthands
  # Greek
  - trigger: ";alpha"
    replace: "α"
  - trigger: ";alpha"
    replace: "Α"
  - trigger: ";beta"
    replace: "β"
  - trigger: ";Beta"
    replace: "Β"
  - trigger: ";gamma"
    replace: "γ"
  - trigger: ";Gamma"
    replace: "Γ"
  - trigger: ";delta"
    replace: "δ"
  - trigger: ";Delta"
    replace: "Δ"
  - trigger: ";epsilon"
    replace: "ϵ"
  - trigger: ";Epsilon"
    replace: "Ε"
  - trigger: ";zeta"
    replace: "ζ"
  - trigger: ";Zeta"
    replace: "Ζ"
  - trigger: ";eta"
    replace: "η"
  - trigger: ";Eta"
    replace: "Η"
  - trigger: ";theta"
    replace: "θ"
  - trigger: ";Theta"
    replace: "Θ"
  - trigger: ";iota"
    replace: "ι"
  - trigger: ";Iota"
    replace: "I"
  - trigger: ";kappa"
    replace: "κ"
  - trigger: ";Kappa"
    replace: "Κ"
  - trigger: ";lambda"
    replace: "λ"
  - trigger: ";Lambda"
    replace: "Λ"
  - trigger: ";mu"
    replace: "μ"
  - trigger: ";Mu"
    replace: "Μ"
  - trigger: ";nu"
    replace: "ν"
  - trigger: ";Nu"
    replace: "Ν"
  - trigger: ";xi"
    replace: "ξ"
  - trigger: ";Xi"
    replace: "Ξ"
  - trigger: ";omicron"
    replace: "ο"
  - trigger: ";Omicron"
    replace: "Ο"
  - trigger: ";pi"
    replace: "π"
  - trigger: ";Pi"
    replace: "Π"
  - trigger: ";rho"
    replace: "ρ"
  - trigger: ";Rho"
    replace: "Ρ"
  - trigger: ";sigma"
    replace: "σ"
  - trigger: ";Sigma"
    replace: "Σ"
  - trigger: ";tau"
    replace: "τ"
  - trigger: ";Tau"
    replace: "Τ"
  - trigger: ";upsilon"
    replace: "υ"
  - trigger: ";Upsilon"
    replace: "Υ"
  - trigger: ";phi"
    replace: "ϕ"
  - trigger: ";Phi"
    replace: "Φ"
  - trigger: ";chi"
    replace: "χ"
  - trigger: ";Chi"
    replace: "Χ"
  - trigger: ";psi"
    replace: "ψ"
  - trigger: ";Psi"
    replace: "Ψ"
  - trigger: ";omega"
    replace: "ω"
  - trigger: ";Omega"
    replace: "Ω"
  - trigger: ";varepsilon"
    replace: "ε"
  - trigger: ";varkappa"
    replace: "ϰ"
  - trigger: ";varphi"
    replace: "φ"
  - trigger: ";varpi"
    replace: "ϖ"
  - trigger: ";varrho"
    replace: "ϱ"
  - trigger: ";varsigma"
    replace: "ς"
  - trigger: ";vartheta"
    replace: "ϑ"


  - trigger: ";in "
    replace: "∈ "

  - trigger: ";int"
    replace: "∫"

  # Analysis
  - trigger: ";times"
    replace: "×"
  - trigger: ";div"
    replace: "÷"
  - trigger: ";infty"
    replace: "∞"
  - trigger: ";nabla"
    replace: "∇"
# \partial	∂
# \sum	∑
# \prod	∏
# \coprod	∐
# \int	∫
# \iint	∬
# \iiint	∭
# \iiiint	⨌
# \oint	∮
# \surfintegral	∯
# \volintegral	∰
# \Re	ℜ
# \Im	ℑ
# \wp	℘
# \mp	∓
# \langle	⟨
# \rangle	⟩
# \lfloor	⌊
# \rfloor	⌋
# \lceil	⌈
# \rceil	⌉

# Greek
# # Relation
# \neq	≠
# \equiv	≡
# \not\equiv	≢
# \leq	≤
# \geq	≥
# \leqq	≦
# \geqq	≧
# \lneqq	≨
# \gneqq	≩
# \leqslant	⩽
# \geqslant	⩾
# \ll	≪
# \gg	≫
# \nless	≮
# \ngtr	≯
# \nleq	≰
# \ngeq	≱
# \lessequivlnt	≲
# \greaterequivlnt	≳
# \prec	≺
# \succ	≻
# \preccurlyeq	≼
# \succcurlyeq	≽
# \precapprox	≾
# \succapprox	≿
# \nprec	⊀
# \nsucc	⊁
# \sim	∼
# \not\sim	≁
# \simeq	≃
# \not\simeq	≄
# \backsim	∽
# \lazysinv	∾
# \wr	≀
# \cong	≅
# \not\cong	≇
# \approx	≈
# \not\approx	≉
# \approxeq	≊
# \approxnotequal	≆
# \tildetrpl	≋
# \allequal	≌
# \asymp	≍
# \doteq	≐
# \doteqdot	≑
# \lneq	⪇
# \gneq	⪈
# \preceq	⪯
# \succeq	⪰
# \precneqq	⪵
# \succneqq	⪶
# # Sets and Logic
# \emptyset	∅
# \in	∈
# \notin	∉	\not\in	∉
# \ni	∋
# \not\ni	∌
# \subset	⊂
# \subseteq	⊆
# \not\subset	⊄
# \not\subseteq	⊈
# \supset	⊃
# \supseteq	⊇
# \not\supset	⊅
# \not\supseteq	⊉
# \subsetneq	⊊
# \supsetneq	⊋
# \exists	∃
# \nexists	∄	\not\exists	∄
# \forall	∀
# \aleph	ℵ
# \beth	ℶ
# \neg	¬
# \wedge	∧
# \vee	∨
# \veebar	⊻
# \land	∧
# \lor	∨
# \top	⊤
# \bot	⊥
# \cup	∪
# \cap	∩
# \bigcup	⋃
# \bigcap	⋂
# \setminus	∖
# \therefore	∴
# \because	∵
# \Box	□
# \models	⊨
# \vdash	⊢
# # Arrow
# \rightarrow	→	\Rightarrow	⇒
# \leftarrow	←	\Leftarrow	⇐
# \uparrow	↑	\Uparrow	⇑
# \downarrow	↓	\Downarrow	⇓
# \nwarrow	↖	\nearrow	↗
# \searrow	↘	\swarrow	↙
# \mapsto	↦
# \to	→
# \leftrightarrow	↔	\hookleftarrow	↩
# \Leftrightarrow	⇔
# \rightarrowtail	↣	\leftarrowtail	↢
# \twoheadrightarrow	↠	\twoheadleftarrow	↞
# \hookrightarrow	↪	\hookleftarrow	↩
# \rightsquigarrow	⇝
# \rightleftharpoons	⇌	\leftrightharpoons	⇋
# \rightharpoonup	⇀	\rightharpoondown	⇁
# # Blackboard Bold, Fraktur
# \mathbb{a}	𝕒	\mathbb{A}	𝔸
# \mathbb{b}	𝕓	\mathbb{B}	𝔹
# \mathbb{c}	𝕔	\mathbb{C}	ℂ
# \mathbb{d}	𝕕	\mathbb{D}	𝔻
# \mathbb{e}	𝕖	\mathbb{E}	𝔼
# \mathbb{f}	𝕗	\mathbb{F}	𝔽
# \mathbb{g}	𝕘	\mathbb{G}	𝔾
# \mathbb{h}	𝕙	\mathbb{H}	ℍ
# \mathbb{i}	𝕚	\mathbb{I}	𝕀
# \mathbb{j}	𝕛	\mathbb{J}	𝕁
# \mathbb{k}	𝕜	\mathbb{K}	𝕂
# \mathbb{l}	𝕝	\mathbb{L}	𝕃
# \mathbb{m}	𝕞	\mathbb{M}	𝕄
# \mathbb{n}	𝕟	\mathbb{N}	ℕ
# \mathbb{o}	𝕠	\mathbb{O}	𝕆
# \mathbb{p}	𝕡	\mathbb{P}	ℙ
# \mathbb{q}	𝕢	\mathbb{Q}	ℚ
# \mathbb{r}	𝕣	\mathbb{R}	ℝ
# \mathbb{s}	𝕤	\mathbb{S}	𝕊
# \mathbb{t}	𝕥	\mathbb{T}	𝕋
# \mathbb{u}	𝕦	\mathbb{U}	𝕌
# \mathbb{v}	𝕧	\mathbb{V}	𝕍
# \mathbb{x}	𝕩	\mathbb{X}	𝕏
# \mathbb{y}	𝕪	\mathbb{Y}	𝕐
# \mathbb{z}	𝕫	\mathbb{Z}	ℤ
# \mathbb{0}	𝟘
# \mathbb{1}	𝟙
# \mathbb{2}	𝟚
# \mathbb{3}	𝟛
# \mathbb{4}	𝟜
# \mathbb{5}	𝟝
# \mathbb{6}	𝟞
# \mathbb{7}	𝟟
# \mathbb{8}	𝟠
# \mathbb{9}	𝟡
# \mathfrak{a}	𝔞	\mathfrak{A}	𝔄
# \mathfrak{b}	𝔟	\mathfrak{B}	𝔅
# \mathfrak{c}	𝔠	\mathfrak{C}	ℭ
# \mathfrak{d}	𝔡	\mathfrak{D}	𝔇
# \mathfrak{e}	𝔢	\mathfrak{E}	𝔈
# \mathfrak{f}	𝔣	\mathfrak{F}	𝔉
# \mathfrak{g}	𝔤	\mathfrak{G}	𝔊
# \mathfrak{h}	𝔥	\mathfrak{H}	ℌ
# \mathfrak{i}	𝔦	\mathfrak{I}	ℑ
# \mathfrak{j}	𝔧	\mathfrak{J}	𝔍
# \mathfrak{k}	𝔨	\mathfrak{K}	𝔎
# \mathfrak{l}	𝔩	\mathfrak{L}	𝔏
# \mathfrak{m}	𝔪	\mathfrak{M}	𝔐
# \mathfrak{n}	𝔫	\mathfrak{N}	𝔑
# \mathfrak{o}	𝔬	\mathfrak{O}	𝔒
# \mathfrak{p}	𝔭	\mathfrak{P}	𝔓
# \mathfrak{q}	𝔮	\mathfrak{Q}	𝔔
# \mathfrak{r}	𝔯	\mathfrak{R}	ℜ
# \mathfrak{s}	𝔰	\mathfrak{S}	𝔖
# \mathfrak{t}	𝔱	\mathfrak{T}	𝔗
# \mathfrak{u}	𝔲	\mathfrak{U}	𝔘
# \mathfrak{v}	𝔳	\mathfrak{V}	𝔙
# \mathfrak{x}	𝔵	\mathfrak{X}	𝔛
# \mathfrak{y}	𝔶	\mathfrak{Y}	𝔜
# \mathfrak{z}	𝔷	\mathfrak{Z}	ℨ
# # Subscripts and superscripts
# _0	₀	^0	⁰
# _1	₁	^1	¹
# _2	₂	^2	²
# _3	₃	^3	³
# _4	₄	^4	⁴
# _5	₅	^5	⁵
# _6	₆	^6	⁶
# _7	₇	^7	⁷
# _8	₈	^8	⁸
# _9	₉	^9	⁹
# _+	⁺	^+	⁺
# _-	⁻	^-	⁻
# _(	₍	^(	⁽
# _)	₎	^)	⁾
# _a	ₐ	^a	ᵃ
# ^b	ᵇ
# ^c	ᶜ
# ^d	ᵈ
# _e	ₑ	^e	ᵉ
# ^f	ᶠ
# ^g	ᵍ
# _h	ₕ	^h	ʰ
# _i	ᵢ	^i	^i	ⁱ
# _j	ⱼ	^j	ʲ
# _k	ₖ	^k	ᵏ
# _l	ₗ	^l	ˡ
# _m	ₘ	^m	ᵐ
# _n	ₙ	^n	ⁿ
# _o	ₒ	^o	ᵒ
# _p	ₚ	^p	ᵖ
# _r	ᵣ	^r	ʳ
# _s	ₛ	^s	ˢ
# _t	ₜ	^t	ᵗ
# _u	ᵤ	^u	ᵘ
# _v	ᵥ	^v	ᵛ
# ^w	ʷ
# _x	ₓ	^x	ˣ
# ^y	ʸ
# ^z	ᶻ
# # Misc
# \mp	∓
# \dotplus	∔
# \bullet	∙
# \cdot	⋅
# \oplus	⊕
# \ominus	⊖
# \otimes	⊗
# \oslash	⊘
# \odot	⊙
# \circ	∘
# \surd	√
# \propto	∝
# \angle	∠
# \measuredangle	∡
# \sphericalangle	∢
# \mid	∣
# \nmid	∤	\not\mid	∤
# \parallel	∥
# \nparallel	∦	\not\parallel	∦
# \flat	♭
# \natural	♮
# \sharp
