#!/usr/bin/env sh

echo $1
echo $2

if [ "$(kitty @ ls | grep -c '"title": "vim-test-output')" -eq 0 ];
then
  kitty @ --to "$KITTY_LISTEN_ON" new-window --new-tab --cwd $1 --title "vim-test-output" "$SHELL -c \"$2\""
fi

kitty @ --to "$KITTY_LISTEN_ON" send-text --match title:"vim-test-output" "$2\x0d"
