-- TODO: autocommand to reload scratchpad.lua on demand

-- TODO: Open GitHub page for Neovim help page
--   P1: Where are the help pages loaded for Neovim?
--       Associate with Neovim GitHub page.
--       open that page on master/main
--
--        if :Blame is used in a help file
--        then -> vim.ui.open("https://github.com/neovim/neovim/blame/master/runtime/doc/diagnostic.txt#L70")
--
--        Future improvement ideas:
--          - handle plugins. can I use the filepath of the absolute path of the help file to determine a git directory?
--            Use git remote?
--            e.g.,
--          --       filepath: /opt/homebrew/Cellar/neovim/0.10.1/share/nvim/runtime/doc/ -> neovim/neovim github link (https://github.com/neovim/neovim/blame/master)
--          --       filepath: ~/.local/share/nvim/lazy/{plugin}/doc/

--
-- TODO: Replace fugitive's :GBrowse with a GitHub blame version.
--
-- TODO: improve :FileName commpand. Replace pbcopy with Neovim buffers.
--
-- TODO: command to open .local/share/nvim/ local dir
--
-- TODO: Neovim's telescope should grep all of help, not just search help tags
--
-- TODO: disable Luacheck line length
--
-- TODO:
