-- -- Bind keys with keyDown and keyUp events
-- hs.hotkey.bind({ "cmd", "alt" }, "h", function()
--   startMoving("h")
-- end, function()
--   stopMoving()
-- end)
--
-- hs.hotkey.bind({ "cmd", "alt" }, "l", function()
--   startMoving("l")
-- end, function()
--   stopMoving()
-- end)
--
-- hs.hotkey.bind({ "cmd", "alt" }, "k", function()
--   startMoving("k")
-- end, function()
--   stopMoving()
-- end)
--
-- hs.hotkey.bind({ "cmd", "alt" }, "j", function()
--   startMoving("j")
-- end, function()
--   stopMoving()
-- end)
--
-- -- Resize bindings
